### ISSUE TITLE
Module (updatecenter) version information not found in the database.

### ISSUE THREAD

**Issue by jimbolinos** [damanic/ls1-module-updatecenter#9]
Hi Matt,

Just tried to update and came up with the following error (via backend update, and SSH)

_Module (updatecenter) version information not found in the database._

I've currently got updatecenter 1.2.13 running. I did recently change the DB password, if that may be the cause, otherwise nothing I can think of?

Cheers,
James
![updatecenter-version](https://cloud.githubusercontent.com/assets/20691325/17195734/96a4f7b6-5457-11e6-84ba-41f63338e803.jpg)

**Comment by damanic** [comment]
Hi James,

This usually happens when your install is looking at the LS marketplace for an update, and your installed version is a newer release from github.

Can you confirm all is shown as compatible in System->Settings->Repo Updates -> Status (tab)  

![capture](https://cloud.githubusercontent.com/assets/5227303/17201214/d437586c-54cf-11e6-90f2-f4b5174ca246.PNG)

I that checks out, make sure your repo config is set to fetch updatecenter from github 
Eg.

```
'updatecenter' => array(
                        'owner' => 'damanic',
                        'repo' => 'ls1-module-updatecenter',
                        'default_allow_update' => true,
                        'view_info_url' => 'https://github.com/damanic/ls1-module-updatecenter/blob/master/readme.md',
                        'view_releases_url' => 'https://github.com/damanic/ls1-module-updatecenter/releases',
                    ),
```

**Comment by jimbolinos** [comment]
Seems to be working without issue today for some reason - a glitch in the matrix perhaps!
